spring:
  application:
    name: "thrift-limit"

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}

  jpa:
    show-sql: ${SHOW_SQL:false}
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: ${FORMAT_SQL:false}

springdoc:
  override-with-generic-response: false

server:
  port: ${LIMIT_PORT:8080}

transaction:
  url: ${TRANSACTION_URL}

currencyapi:
  url: ${CURRENCYAPI_URL}