create table currencies
(
    id          bigint primary key generated by default as identity,
    code        varchar(8)               not null,
    rate        numeric(8, 2)            not null,
    last_update timestamp with time zone not null
);